# Generated by Django 5.0.7 on 2024-07-30 12:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sun', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameresult',
            old_name='session',
            new_name='sid',
        ),
        migrations.RemoveField(
            model_name='gameresult',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='gameresult',
            name='created_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='result_data',
            field=models.CharField(default='', max_length=1),
        ),
    ]
