# Generated by Django 5.0.7 on 2024-07-30 14:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sun', '0002_rename_session_gameresult_sid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameresult',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='gameresult',
            name='created_time',
        ),
        migrations.AddField(
            model_name='gameresult',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
