# Generated by Django 5.0.7 on 2024-07-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sun', '0003_remove_gameresult_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberlist',
            name='current_number',
            field=models.IntegerField(default=0),
        ),
    ]
