# Generated by Django 5.0.7 on 2024-07-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sun', '0004_numberlist_current_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberlist',
            name='max_number',
            field=models.IntegerField(default=0),
        ),
    ]
