# Generated by Django 5.0.7 on 2024-08-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sun', '0005_numberlist_max_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='counter_11',
            field=models.IntegerField(default=0),
        ),
    ]
